INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'shop for fidget spinners', 'toBuy', 'me like the fidgety toy', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'shop for clothes', 'toBuy', 'running out of whitey tideys', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'buy groceries', 'toBuy', 'eggs, tomatoes, bacon, cheese, mayo', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'buy new computer parts', 'toBuy', 'Need new graphics card for 4k gaming', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'buy new keyboard', 'toBuy', 'need macOS keyboard for LHL', FALSE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'watch Game of Thrones', 'toWatch', 'Cersei Lannister did not deserve a peaceful death', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'watch Avengers Endgame', 'toWatch', 'Batman is my favourite avenger lol', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'watch Frozen 2', 'toWatch', 'Let it go, let it go, cant hold it back anymore', FALSE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'watch mayukos tech videos on youtube', 'toWatch', 'How to bargain for your salary', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'read LHL Job Seekers Agreement', 'toRead','make sure you understand everything', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'read cracking the coding interview', 'toRead', 'read through the first chapter', FALSE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'read through midterm requirements', 'toRead', 'dont forget the major requirements of the project', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'date with da gf', 'toEat', 'Cactus Club Cafe', FALSE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'coffee with mentor', 'toEat', 'im hungry', FALSE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'eat lunch with family', 'toEat', 'July 1st lunch', TRUE);
INSERT INTO todo_lists (user_id, title, category, description, status) VALUES (1, 'eat dinner with my LHL rubber ducky', 'toEat', 'Im a loner', FALSE);
