INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'shop for fidget spinners', 'toBuy', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'shop for clothes', 'toBuy', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'buy groceries', 'toBuy', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'buy new computer parts', 'toBuy', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'buy new keyboard', 'toBuy', FALSE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'watch Game of Thrones', 'toWatch', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'watch Avengers Endgame', 'toWatch', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'watch Frozen 2', 'toWatch', FALSE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'watch mayukos tech videos on youtube', 'toWatch', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'read LHL Job Seekers Agreement', 'toRead', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'read cracking the coding interview', 'toRead', FALSE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'read through midterm requirements', 'toRead', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'date with da gf', 'toEat', FALSE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'coffee with mentor', 'toEat', FALSE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'eat lunch with family', 'toEat', TRUE);
INSERT INTO todo_lists (user_id, title, category, status) VALUES (1, 'eat dinner with my LHL rubber ducky', 'toEat', FALSE);
